title: [WW's Portfolio]
tagline: [William Wang's portfolio website]
description: [This website is for showcasing projects and works I have done or are working on.]
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
